=== CheukBinLi/original/original-db-manager/src/main/resources/META-INF/dtd/Query.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT QueryList (Alias*,Join*,Query*)>
<!--<!ELEMENT Context (CachePool,Bean*,Intercept*,ScanToPack*,CloneModel)>-->
<!ELEMENT Alias EMPTY><!--别名-->
<!ELEMENT Join (#PCDATA)><!--引用-->
<!ELEMENT Query (#PCDATA)><!--sql/hql-->

<!--QueryList-->
<!ATTLIST QueryList package CDATA #REQUIRED>
<!--Alias-->
<!ATTLIST Alias name CDATA #REQUIRED><!--实体类全名-->
<!ATTLIST Alias Alias CDATA #REQUIRED><!--SQL/HQL 语句中的实体类别名-->
<!--where-->
<!ATTLIST Join name CDATA #REQUIRED><!--名字-->
<!--Query-->
<!ATTLIST Query name CDATA #REQUIRED><!--实体类全名-->
<!ATTLIST Query type (HQL|SQL) #REQUIRED><!--语句类型：HQL/SQL-->
<!ATTLIST Query freemarkFormat (false|true) #REQUIRED><!--是否使用FREEMARK标签格式化-->
<!ATTLIST Query resultType CDATA #IMPLIED><!--实体类全名-->
<!ATTLIST Query Alias (true|false) #REQUIRED><!--是否使用了类别名-->
<!ATTLIST Query joinRef CDATA #IMPLIED><!--join引用-->
<!ATTLIST Query joinTag CDATA #IMPLIED><!--替换标记-->

=== CheukBinLi/original/original-db-manager/src/main/resources/dtd/demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE QueryList SYSTEM "Query.dtd">
<QueryList package="project.master.user.User">
	<Alias name="project.master.user.User" Alias="User" />
	<Alias name="project.freehelp.common.entity.Dictionary" Alias="Dictionary" />
	<Join name="defaultWhereList">
		<![CDATA[ 
			<#if id??>
				<#if like??>
					and A.id like '%'||:id||'%'
				<#else>
					and A.id=:id
				</#if>
			</#if>
			<#if phone??>
				<#if like??>
					and A.phone like '%'||:phone||'%'
				<#else>
					and A.phone=:phone
				</#if>
			</#if>
			<#if password??>
				<#if like??>
					and A.password like '%'||:password||'%'
				<#else>
					and A.password=:password
				</#if>
			</#if>
			<#if lastLogin??>
				<#if like??>
					and A.lastLogin like '%'||:lastLogin||'%'
				<#else>
					and A.lastLogin=:lastLogin
				</#if>
			</#if>
			<#if status??>
				<#if like??>
					and A.status like '%'||:status||'%'
				<#else>
					and A.status=:status
				</#if>
			</#if>
		]]>
	</Join>
	<Query name="list" type="HQL" freemarkFormat="true" Alias="true" joinRef="defaultWhereList" joinTag="@WHERE@">
		<![CDATA[ 
			FROM User A 
			WHERE 
			1=1
			@WHERE@
		]]>
	</Query>
	<Query name="AAX" type="HQL" freemarkFormat="true" Alias="true">
		<!--测试 -->
		SELECT A.phone,(SELECT D.value FROM Dictionary D WHERE D.id='1') as xValue FROM User A
	</Query>
	<Query name="checkUser" type="HQL" freemarkFormat="false" Alias="true">
		SELECT COUNT(1) FROM User A WHERE A.phone=:phone
	</Query>
	<Query name="login" type="HQL" freemarkFormat="false" Alias="true">
		FROM User A WHERE A.phone=:phone and A.password=:password
	</Query>
</QueryList>
